homeassistant:
  # Name of the location where Home Assistant is running
  name: Hechtweg 8
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  # Customization file
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Adding the custom UI elements from https://github.com/andrey-git/home-assistant-custom-ui
customizer:
  custom_ui: local

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
recorder:
  purge_keep_days: 60

history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Sensors
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml

notify:

http:
  api_password: !secret api_password
  ip_ban_enabled: Yes
  login_attempts_threshold: 5

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
weblink:
  entities: !include weblinks.yaml