# Track the sun
sun:

sensor:
  # Track the moon
  - platform: moon

  # Weather prediction
  - platform: zamg
    station_id: 11010
    name: hoersching
    monitored_conditions:
      - temperature
      - humidity
      - pressure
      - wind_speed
      - wind_bearing
      - wind_max_speed
      - sun_last_hour
      - precipitation
      - dewpoint

group:
  weather:
    name: Wetter
    control: hidden
    icon: mdi:weather-partlycloudy
    entities:
      - sun.sun
      - sensor.moon
      - sensor.hoersching_temperature
      - sensor.hoersching_humidity
      - sensor.hoersching_pressure
      - sensor.hoersching_wind_speed
      - sensor.hoersching_wind_max_speed
      - sensor.hoersching_wind_bearing
      - sensor.hoersching_sun_last_hour
      - sensor.hoersching_precipitation
      - sensor.hoersching_dewpoint

homeassistant:
  customize:
    sensor.moon:
      friendly_name: Mond
    sun.sun:
      friendly_name: Sonne
    sensor.hoersching_temperature:
      device_class: temperature
      friendly_name: Hörsching Temperatur
      group:
        group.weather:
          friendly_name: Temperatur
    sensor.hoersching_humidity:
      friendly_name: Hörsching Luftfeuchtigkeit
      icon: mdi:water-percent
      group:
        group.weather:
          friendly_name: Luftfeuchtigkeit
    sensor.hoersching_pressure:
      friendly_name: Hörsching Luftdruck
      icon: mdi:gauge
      group:
        group.weather:
          friendly_name: Luftdruck
    sensor.hoersching_wind_speed:
      friendly_name: Hörsching Windgeschwindigkeit
      icon: mdi:weather-windy-variant
      group:
        group.weather:
          friendly_name: Windgeschwindigkeit
    sensor.hoersching_wind_bearing:
      friendly_name: Hörsching Windrichtung
      icon: mdi:compass-outline
      group:
        group.weather:
          friendly_name: Windrichtung
    sensor.hoersching_wind_max_speed:
      friendly_name: Hörsching Maximale Windgeschwindigkeit
      icon: mdi:weather-windy
      group:
        group.weather:
          friendly_name: Maximale Windgeschwindigkeit
    sensor.hoersching_sun_last_hour:
      friendly_name: Hörsching Sonnenschein
      icon: mdi:weather-partlycloudy
      group:
        group.weather:
          friendly_name: Sonnenschein
    sensor.hoersching_precipitation:
      friendly_name: Hörsching Niederschlag
      icon: mdi:weather-snowy-rainy
      unit_of_measurement: mm
      group:
        group.weather:
          friendly_name: Niederschlag
    sensor.hoersching_dewpoint:
      friendly_name: Hörsching Taupunkt
      group:
        group.weather:
          friendly_name: Taupunkt
